CREATE DATABASE facecool

CREATE TABLE personne (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(100),
prenom VARCHAR(100),
url_photo VARCHAR(200),
date_naissance DATE,
statut_couple VARCHAR(50),
musique_id INT UNSIGNED FOREIGN KEY,
hobbies_id INT UNSIGNED FOREIGN KEY,
relation_id INT UNSIGNED FOREIGN KEY );

CREATE TABLE musique (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
type VARCHAR (100));

CREATE TABLE hobby (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
type VARCHAR (100));

CREATE TABLE relation (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
type VARCHAR(100));

